# Generated by Django 3.2.3 on 2021-08-24 00:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import main.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('algorithm', models.CharField(blank=True, max_length=30, null=True)),
                ('sparkID', models.IntegerField(blank=True, null=True)),
                ('dataSetFile', models.FileField(blank=True, null=True, upload_to=main.models.upload_path_handler)),
                ('trainedDataFile', models.FileField(blank=True, null=True, upload_to=main.models.upload_path2_handler)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
